name: finance_manager
description: Fin Manager - Android & Web with synced data via Google Drive CSV.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  indian_sms_filter:
    path: ../indian_sms_filter
  google_sign_in: ^6.2.2
  googleapis: ^13.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
